=== Riabchenko/Progects_for_EPAM/autumn2015/CompanyXML/out/production/CompanyXML/com/intellect25/company/resources/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://com.intellect25.company.resources4/mns"
           xmlns:mns="http://com.intellect25.company.resources4/mns">

  <xs:element name="company" type="mns:companyType">

    <xs:unique name="myId">
      <xs:selector xpath=".//*"/>
      <xs:field xpath="@id"/>
    </xs:unique>

  </xs:element>

  <xs:complexType name="companyType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="mns:otherType" name="other"/>
      <xs:element type="mns:managerType" name="manager"/>
      <xs:element type="mns:workerType" name="worker"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="otherType">
    <xs:complexContent>
    <xs:extension base="mns:employee">
      <xs:sequence>
        <xs:element type="xs:string" name="info"/>
      </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="managerType">
    <xs:complexContent>
      <xs:extension base="mns:employee">
      <xs:sequence>
        <xs:element type="mns:listWorkers" name="listWorkers" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="employee" abstract="true">
    <xs:sequence>
      <xs:element type="xs:string" name="firstName"/>
      <xs:element type="xs:string" name="middleName"/>
      <xs:element type="xs:string" name="lastName"/>
      <xs:element type="xs:date" name="birthday"/>
      <xs:element type="xs:date" name="dateOfGetJob"/>
    </xs:sequence>
    <xs:attribute type="mns:id" name="id"/>
  </xs:complexType>

  <xs:complexType name="listWorkers">
    <xs:sequence>
      <xs:element type="mns:id" name="workerId" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="id">
    <xs:restriction base="xs:int">
      <xs:pattern value="[0-9]{1,4}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="workerType">
    <xs:complexContent>
     <xs:extension base="mns:employee"/>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== Riabchenko/Progects_for_EPAM/autumn2015/CompanyXML/out/production/CompanyXML/com/intellect25/company/resources/company000.xml
<?xml version="1.0" ?>
<mns:company xmlns:mns="http://com.intellect25.company.resources4/mns"
             xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
             xs:schemaLocation="http://com.intellect25.company.resources4/mns company.xsd">
    <mns:manager id="2">
        <mns:firstName>string</mns:firstName>
        <mns:middleName>string</mns:middleName>
        <mns:lastName>B</mns:lastName>
        <mns:birthday>2006-08-19+03:00</mns:birthday>
        <mns:dateOfGetJob>2009-05-16</mns:dateOfGetJob>
        <mns:listWorkers>
            <mns:workerId>3</mns:workerId>
            <mns:workerId>4</mns:workerId>
        </mns:listWorkers>
    </mns:manager>
    <mns:other id="1">
        <mns:firstName>string</mns:firstName>
        <mns:middleName>string</mns:middleName>
        <mns:lastName>C</mns:lastName>
        <mns:birthday>2008-09-29</mns:birthday>
        <mns:dateOfGetJob>2014-09-19</mns:dateOfGetJob>
        <mns:info>string</mns:info>
    </mns:other>
    <mns:other id="6">
        <mns:firstName>string</mns:firstName>
        <mns:middleName>string</mns:middleName>
        <mns:lastName>D</mns:lastName>
        <mns:birthday>2008-09-29</mns:birthday>
        <mns:dateOfGetJob>2016-09-19</mns:dateOfGetJob>
        <mns:info>string</mns:info>
    </mns:other>
    <mns:worker id="3">
        <mns:firstName>string</mns:firstName>
        <mns:middleName>string</mns:middleName>
        <mns:lastName>A</mns:lastName>
        <mns:birthday>2003-08-09</mns:birthday>
        <mns:dateOfGetJob>2014-09-13</mns:dateOfGetJob>
    </mns:worker>
    <mns:worker id="4">
        <mns:firstName>string</mns:firstName>
        <mns:middleName>string</mns:middleName>
        <mns:lastName>string</mns:lastName>
        <mns:birthday>2003-08-09+03:00</mns:birthday>
        <mns:dateOfGetJob>2011-09-13</mns:dateOfGetJob>
    </mns:worker>
    <mns:worker id="5">
        <mns:firstName>string</mns:firstName>
        <mns:middleName>string</mns:middleName>
        <mns:lastName>V</mns:lastName>
        <mns:birthday>2003-08-09+03:00</mns:birthday>
        <mns:dateOfGetJob>2015-09-13+03:00</mns:dateOfGetJob>
    </mns:worker>
    <mns:manager id="12">
        <mns:firstName>ddd</mns:firstName>
        <mns:middleName>fff</mns:middleName>
        <mns:lastName>SSS</mns:lastName>
        <mns:birthday>1987-03-12</mns:birthday>
        <mns:dateOfGetJob>1999-01-02</mns:dateOfGetJob>
        <mns:listWorkers>
            <mns:workerId>4</mns:workerId>
            <mns:workerId>0</mns:workerId>
        </mns:listWorkers>
    </mns:manager>
</mns:company>
